In [ ]:
import numpy as np

arr1  = np.array([1,2,100,4,5]   )

arr2  = np.array([[1,2,3] ,
                [4,5,6] ] )
print(arr1)
print(arr2)
arr1_mod = arr1[1:4]
arr1_mod[0] =100
print(arr1_mod)

In [3]:
lst = np.array([10, 20, 30, 40])
values = lst[[0,3]]
print(values)

[10 40]


In [7]:
print(arr2[[0,1], [1,2]])
print(arr2)


print(arr2[arr2<2])
arr2[arr2>2] =0
print(arr2)

[2 6]
[[1 2 3]
 [4 5 6]]
[1]
[[1 2 0]
 [0 0 0]]


In [10]:
arr =np.array([[10,20,30], [100,200,300]])

for i in arr:
    print(i)
    for j in i:
        print(j)





[10 20 30]
10
20
30
[100 200 300]
100
200
300
10
20
30
100
200
300


In [11]:
for i in np.nditer(arr):
    print(i)

10
20
30
100
200
300
