In [4]:
import numpy as np

lst =[12,37,67,87,55.5,'True']
arr = np.array(lst,dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

[12 37 67 87 55]
<class 'numpy.ndarray'>
int32


In [7]:
lst_mixd =[12,37,67,87,55.5,'True',33]
arr = np.array(lst_mixd)

print(arr)
print(type(arr))
print(arr.dtype)

['12' '37' '67' '87' '55.5' 'True' '33']
<class 'numpy.ndarray'>
<U32


In [8]:
matrix = [[1,2,3],
      [4,5,6],
      [7,8,9]]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64


In [9]:
tpl = (12,55)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

int32
[12 55]
<class 'numpy.ndarray'>
(2,)
1


In [14]:
st = (12,55,77)
print(st)
arr3 = np.array(list(st))
print(arr3.dtype)

print(type(arr3))
print(arr3.shape)
print(arr3.ndim)

(12, 55, 77)
int64
<class 'numpy.ndarray'>
(3,)
1


In [18]:
dc = {'a':10, 'b':20, 'c':30}

#keys to ndarray
keys = dc.keys()
values = dc.values()
items = dc.items()
arr = np.array(list(keys))
print(arr)
print(keys)
print(values)
print(items)
print(dc)
print(type(arr))
print(arr.shape)
print(arr.ndim)


['a' 'b' 'c']
dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
{'a': 10, 'b': 20, 'c': 30}
<class 'numpy.ndarray'>
(3,)
1


_### **from the source file**_

In [19]:
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [21]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [ ]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

In [ ]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [ ]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [ ]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)