In [7]:
import numpy as np
arr = np.zeros((2,3),dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
2
6


In [10]:
arw = np.ones((4,3),dtype=np.int8)
print(arw)
print(arw)
print(type(arw))
print(arw.dtype)
print(arw.shape)
print(arw.ndim)
print(arw.size)



[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12


In [11]:
arw = np.ones((3,4,3),dtype=np.int8)

print(arw)
print(arw)
print(type(arw))
print(arw.dtype)
print(arw.shape)
print(arw.ndim)
print(arw.size)



[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
3
36


In [12]:
arr = np.zeros_like(arw)
print(arr)
print(arr.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
(3, 4, 3)


In [13]:
arr = np.ones_like(arw)
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
(3, 4, 3)


In [16]:
arw = np.empty((4,3),dtype=np.int8)

print(arw)
print(arw)
print(type(arw))
print(arw.dtype)
print(arw.shape)
print(arw.ndim)
print(arw.size)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int8
(4, 3)
2
12


In [18]:
arr3 = np.empty_like(arw) ## arr3 shape same
print(arr3)
print(arr3.shape)

[[  64  -84  117]
 [  70 -119    2]
 [   0    0    0]
 [   0    0    0]]
(4, 3)


In [19]:
arr = np.full((4,3),np.inf)

# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr = np.full_like(arr3,np.inf,dtype=np.float64)

print(arr)
print(arr.shape)
print(arr.dtype)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
(4, 3)
float64


In [22]:
arr4 = np.full((4,3),True)
print(arr)
print(type(arr))
print(arr4.dtype)
print(arr4.shape)
print(arr4.ndim)
print(arr4.size)

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
<class 'numpy.ndarray'>
bool
(4, 3)
2
12
