In [2]:
import numpy as np

arr = np.random.rand(2,3)

print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.3604758  0.52273163 0.58254057]
 [0.04033738 0.68946937 0.94107908]]
<class 'numpy.ndarray'>
int16
(2, 3)
2
6


In [6]:
import numpy as np

arr = np.random.randint(1,30 ,(10,10))

print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[20 29  5  4 22 10 18  9 27  1]
 [29 15 11 28 15 21 29 29 21 10]
 [ 6  5 19  9 16 26  5 15 24 10]
 [11 14 17 10 11  2 10 10 10 28]
 [12 23  1 27 21  4  6 16  7  1]
 [19  3 26  1  6 14 13  7 16  4]
 [26 12 27 26  2  4 21  6 25 28]
 [17 28 24 13 18 25 17 24  8 14]
 [18 19  1 15  2 27 11 12  6 20]
 [ 7 12 23  7 14 16 27  7  2  6]]
<class 'numpy.ndarray'>
int16
(10, 10)
2
100


In [7]:
import numpy as np

arr = np.random.uniform(1,30 ,(10,10))

print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[28.15278583  5.39410209 22.87926883  8.76250934 26.36147161 27.29798235
   3.43057255 23.49499933 14.54109401  9.15328155]
 [19.03026481  8.66065721  1.33382284 15.1756241   9.17430694 11.66066468
  27.42273574  7.62276877 10.04847083 13.70535368]
 [ 3.55174833 14.45368665 13.6962107  10.19102407  7.20094485 23.40973912
   7.19716914  4.71102695  9.53557205  7.80051059]
 [19.82710345 20.44755578  5.08972836  7.4212903  19.36497667 20.75548242
   4.26729148  4.32989515  7.04622001 16.65083952]
 [18.15031233  1.31254688 11.5564398   9.00187795  4.30991842 26.03392933
   6.34854229 29.87541702 23.66141295  1.09079161]
 [22.12874296 24.02253085 24.97401026  2.75808072 19.68465222 16.85838722
  20.28140781  5.29791687 20.53258849  2.81008668]
 [14.08284658 14.84097553  4.3078665  18.98241272  4.34665128  2.54618649
  10.42321433 19.17365937 24.97116442  6.26856779]
 [25.73839875 17.40818674 21.213551   11.91557706 24.39350976  5.20880353
  10.29096001 23.75636019 18.35274826  9.56696328]
