In [4]:
import numpy as np

arr = np.arange(1 , 10,1).reshape(3,3)

print(arr)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)
2
9


In [6]:
import numpy as np

arr = np.linspace(1 , 10,15)

print(arr)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
<class 'numpy.ndarray'>
float64
(15,)
1
15


In [ ]:
arr = np.logspace(1 , 10,15)

print(arr)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

In [7]:
arr = np.logspace(0,4,6, base =2)

print(arr)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
<class 'numpy.ndarray'>
float64
(6,)
1
6
