In [22]:
import numpy as np

arr1  = np.array([1,2,3,4,5]   )

arr2  = np.array([[1,2,3] ,
                [4,5,6] ] )



print(arr1)
print()
print(arr2)

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]


In [19]:
#print(arr1[2])
#arr1[2] = 100
#print(arr1[2])

100
100


In [8]:
print(arr2)

print(arr2[0][1])

[[ 10  20  30]
 [100 200 300]]
20


In [9]:
#slicing
#1d = arr[start:end:step]


arr1_MOD = arr1[1:4]
print(arr1_MOD)

[  2 100   4]


In [23]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = arr2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]


In [14]:
col_0 = arr2[:: ,0:1]
print(col_0)

[[ 10]
 [100]]
