In [1]:
import numpy as np

arr = np.array([1,2,3])
print(arr.ndim)

1


In [2]:
arr = np.array([1, 2.5, 3])
print(arr.dtype)

float64


In [3]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [4]:
arr2 = np.full((2,2), np.inf)
print(arr2)

[[inf inf]
 [inf inf]]


In [5]:
arr3 = np.array([[10,20,30],[40,50,60]])
print(arr3[:,1])

[20 50]


In [6]:
import numpy as np
arr = np.random.rand(2, 3)
print(arr)

[[0.38123901 0.47303471 0.79894741]
 [0.76994739 0.24178974 0.77724551]]


In [7]:
arr5 = np.array([1,2,3,4,5])
arr5[1:4] = 0
print(arr5)

[1 0 0 0 5]
