
# Module covered topic

_Numpy - Nd Array Object.
Numpy - Data Types.
Numpy - Array Attributes.
Numpy - Array Creation Routines.
Numpy - Array From Existing.
Data Array From Numerical Ranges.
Numpy - Indexing & Slicing.
Numpy - Advanced Indexing.
Numpy - Broadcasting.
Numpy - Iterating Over Array
Numpy - Array Manipulation.
Numpy - Conditional operations with all and any
Numpy - String Functions.
Numpy - Mathematical Functions.
Numpy - Arithmetic Operations.
Numpy - Statistical Functions.
Sort, Search & Counting Functions.
Numpy - Linear Algebra_

In [3]:
import numpy as np
from fontTools.misc.cython import returns
from setuptools.namespaces import flatten

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

d = np.dot(A, B)
print(d)

[[ 58  64]
 [139 154]]


In [4]:
d1 =np.linalg.inv(d)
print(d1)

[[ 4.27777778 -1.77777778]
 [-3.86111111  1.61111111]]


In [5]:
d2 = np.linalg.matrix_transpose(d1)
print(d2)

[[ 4.27777778 -3.86111111]
 [-1.77777778  1.61111111]]


In [6]:
#`1
arr = np.random.randint(1,21, size=(5,5))
print(arr)



[[ 3  5  3  1  9]
 [ 1 14  1  6 16]
 [15  8 16 19 11]
 [12  8  4 13 12]
 [12  7  4  1 16]]


In [7]:
arr[:, 1]=1
print(arr)

[[ 3  1  3  1  9]
 [ 1  1  1  6 16]
 [15  1 16 19 11]
 [12  1  4 13 12]
 [12  1  4  1 16]]


In [8]:
#2

arr = np.random.randint(1,17, size=(4,4))
print(arr)

[[14 10  4  1]
 [ 4  7 11  4]
 [ 3 14 11 15]
 [ 5  3  6  2]]


In [9]:
np.fill_diagonal(arr,0)
print(arr)

[[ 0 10  4  1]
 [ 4  0 11  4]
 [ 3 14  0 15]
 [ 5  3  6  0]]


In [10]:
arr[:, 2] = 1
print(arr)
print()
arr[2, :] = 1
print(arr)

[[ 0 10  1  1]
 [ 4  0  1  4]
 [ 3 14  1 15]
 [ 5  3  1  0]]

[[ 0 10  1  1]
 [ 4  0  1  4]
 [ 1  1  1  1]
 [ 5  3  1  0]]


In [11]:
#3
arr = np.random.randint(1,36, size=(5,5))
print(arr)

[[18  2 24  1 27]
 [23  7  9 23 34]
 [27  9 32 30 24]
 [27 28 16 33 21]
 [33  6 25 28  1]]


In [12]:
print(arr[2:5, 1:4])


[[ 9 32 30]
 [28 16 33]
 [ 6 25 28]]


In [13]:
#3
arr = np.random.randint(1, 36, size=(5, 5))
print(arr)

[[10  9 17 17 17]
 [33 11 17  9 11]
 [35 14 16 29 13]
 [12 14 16 13 11]
 [15 30 16 18  3]]


In [14]:
print(arr[0,:])
print(arr[4, :])
print(arr[1:4, 0])
print(arr[1:4, -1])


[10  9 17 17 17]
[15 30 16 18  3]
[33 35 12]
[11 13 11]


In [15]:
print(arr[0, :])
print(arr[4, :])
print(arr[1:4, 0])
print(arr[1:4, -1])
print()
arr3 = np.concatenate((arr[0, :],arr[-1, :],arr[1:4, 0],arr[1:4, -1] ))
print(arr3)

[10  9 17 17 17]
[15 30 16 18  3]
[33 35 12]
[11 13 11]

[10  9 17 17 17 15 30 16 18  3 33 35 12 11 13 11]


In [16]:
arr1 = np.random.randint(1, 36, size=(3, 4))
arr2 = np.random.randint(1, 36, size=(3, 4))

print(arr1)
print()
print(arr2)

print()


[[32 12  2 12]
 [23 18 11  7]
 [34 29  2 12]]

[[23 30 31 22]
 [18 14 27  4]
 [31 21 29  4]]



In [17]:
# 1
arr1 = np.random.randint(1, 36, size=(3, 4))
arr2 = np.random.randint(1, 36, size=(3, 4))
print(arr1)
print(arr2)
print()
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)


[[32 19  6  7]
 [ 3 26  5 23]
 [14 11 24  4]]
[[17 30 10 24]
 [30 24 32 10]
 [23 28 29 24]]

[[49 49 16 31]
 [33 50 37 33]
 [37 39 53 28]]
[[ 15 -11  -4 -17]
 [-27   2 -27  13]
 [ -9 -17  -5 -20]]
[[544 570  60 168]
 [ 90 624 160 230]
 [322 308 696  96]]
[[1.88235294 0.63333333 0.6        0.29166667]
 [0.1        1.08333333 0.15625    2.3       ]
 [0.60869565 0.39285714 0.82758621 0.16666667]]


In [19]:
#44min
row_sum = np.sum(arr, axis=1)
print(row_sum)
print()
col_sum = np.sum(arr, axis=0)
print(col_sum)


[ 70  81 107  66  82]

[105  78  82  86  55]


In [21]:
arr = np.random.randint(1,25, size=(4,4))
print(arr)
print("Mean =", np.mean(arr))
print("Median =", np.median(arr))
print("Standard Deviation =", np.std(arr))
print("Variance =", np.var(arr))
print(dir(arr))

[[ 1 19 17 24]
 [14  1 14 18]
 [13  1  6 19]
 [19  7 20  1]]
Mean = 12.125
Median = 14.0
Standard Deviation = 7.7852023095100105
Variance = 60.609375
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len_

In [22]:
# 1
arr = np.random.randint(1, 25, size=(3, 3))
arr1 = np.random.randint(1, 25, size=(3,))

print(arr)
print(arr1)
print(arr+arr1)

[[ 1 17 14]
 [ 5  5 14]
 [19 14 15]]
[23 21  5]
[[24 38 19]
 [28 26 19]
 [42 35 20]]


In [24]:
print(arr1[:, np.newaxis])
print()
print(arr1[np.newaxis, :])
print()
print(arr1[:,np.newaxis])
print()
print(arr1)  # 3
print()
arr1.shape
arr2 = arr1.reshape(3, 1) # row =3, col = 1

print(arr - arr2)

[[23]
 [21]
 [ 5]]

[[23 21  5]]

[[23]
 [21]
 [ 5]]

[23 21  5]

[[-22  -6  -9]
 [-16 -16  -7]
 [ 14   9  10]]


In [27]:
arr = np.random.randint(1,10 , size=(3,3))
print(arr)

print(arr.reshape(1,9))
print()
print(arr.reshape(9,1))


[[9 6 4]
 [5 1 5]
 [3 8 6]]
[[9 6 4 5 1 5 3 8 6]]

[[9]
 [6]
 [4]
 [5]
 [1]
 [5]
 [3]
 [8]
 [6]]


In [29]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])
print(np.dot(A, B))

[[ 58  64]
 [139 154]]


In [32]:
arr = np.random.randint(1, 10, size=(5, 5))
print(arr)
flatten_arr = arr.flatten()
print(flatten_arr)
arr2 = flatten_arr.reshape(5,5)
print(arr2)

[[8 1 8 3 2]
 [6 9 8 7 9]
 [6 6 7 4 8]
 [5 5 9 6 9]
 [7 7 5 4 7]]
[8 1 8 3 2 6 9 8 7 9 6 6 7 4 8 5 5 9 6 9 7 7 5 4 7]
[[8 1 8 3 2]
 [6 9 8 7 9]
 [6 6 7 4 8]
 [5 5 9 6 9]
 [7 7 5 4 7]]


In [30]:
# 1
arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

print(arr.reshape(1, 9))
print(arr.reshape(9, 1)) # row = 9 , col = 1

[[5 8 1]
 [7 9 9]
 [7 7 8]]
[[5 8 1 7 9 9 7 7 8]]
[[5]
 [8]
 [1]
 [7]
 [9]
 [9]
 [7]
 [7]
 [8]]


In [33]:
arr = np.random.randint(1,100, size=(5,5))

print(arr)


[[38 35 15 10 29]
 [63 41 65 48 43]
 [72  7 62 13 93]
 [67  4 40 48 15]
 [ 3 15 47 90 47]]


In [36]:
print((arr[arr>10]))
arr[arr>10] = 10
print(arr)

[]
[[10 10 10 10 10]
 [10 10 10 10 10]
 [10  7 10 10 10]
 [10  4 10 10 10]
 [ 3 10 10 10 10]]


In [40]:
import numpy as np

def reshape_matrix(a: list[list[int | float]], new_shape: tuple[int, int]) -> list[list[int | float]]:
    # Write your code here and return a python list after reshaping by using numpy's tolist() method
    arr = np.array(a)

    # Check if total elements match
    if arr.size != new_shape[0] * new_shape[1]:
        return []

    # Reshape and return as list
    arr = arr.reshape(new_shape[0], new_shape[1])
    return arr.tolist()


In [45]:
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
    arr = np.array(matrix)
    arr = arr * scalar
    return arr.tolist()

In [ ]:
def vector_sum(a: list[int | float], b: list[int | float]) -> list[int | float] | int:
    # Check if vectors have the same length
    if len(a) != len(b):
        return -1

    # Compute element-wise sum
    return [a[i] + b[i] for i in range(len(a))]
