In [2]:
from math import remainder
from signal import pthread_sigmask

import numpy as np

from extra_class import matrix

arr = np.random.randint(1, 100, size=(10, 5))
arr.shape

(10, 5)

In [5]:
b = arr.reshape(5,10)
b.shape
b.ndim
b

array([[62, 45, 35, 38, 38, 76, 91, 99, 11,  9],
       [56, 68, 72, 58, 67,  2,  7, 79, 68, 69],
       [56, 46, 81, 95, 50, 41, 95, 37, 75, 85],
       [87,  7, 12, 93, 69, 26, 56,  8, 85, 91],
       [19, 60, 81, 53, 60,  1, 13, 83, 39, 18]], dtype=int32)

In [7]:
flatten = b.flatten()

print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b, order='F')
print(column_wise_flattening)

1
[62 56 56 87 19 45 68 46  7 60 35 72 81 12 81 38 58 95 93 53 38 67 50 69
 60 76  2 41 26  1 91  7 95 56 13 99 79 37  8 83 11 68 75 85 39  9 69 85
 91 18]


In [9]:
a = np.random.randint(1, 10, size =(2,3))
b = np.random.randint(20, 30, size =(2,3))



In [11]:
con = np.concatenate((a, b), axis=0)
print(con)

[[ 1  5  4]
 [ 4  4  6]
 [26 26 20]
 [29 23 21]]


In [12]:
con_row = np.concatenate((a, b), axis=0)
print(con_row)
print()
con_col = np.concatenate((a, b), axis=1)
print(con_col)

[[ 1  5  4]
 [ 4  4  6]
 [26 26 20]
 [29 23 21]]

[[ 1  5  4 26 26 20]
 [ 4  4  6 29 23 21]]


In [14]:
x = np.random.randint(1, 10, size=(2,3))
y = np.random.randint(1, 10, size=(2,3))

r = np.concatenate((x, y), axis=0)
print(r)
print()
#print(x)
#print(y)

[[2 8 4]
 [8 2 7]
 [5 5 7]
 [9 4 9]]




#                            **11.2 ndarray Manipulation - 2**

In [4]:
import numpy as np

mat = np.array([[10, 20, 30],
                [30, 40, 50]])

transpose = mat.T
print(transpose)
print()
print(mat.shape)     # (2, 3)
print(transpose.shape)  # (3, 2)  ← উল্টে গেছে!

[[10 30]
 [20 40]
 [30 50]]

(2, 3)
(3, 2)


In [11]:
a = np.random.randint(1 ,10 , size =(9,))
print(a)
splitted_array = np.split(a,3)
print(splitted_array)
print()
splitted_array = np.split(a,3)
print(splitted_array)

[3 3 6 8 7 4 6 3 2]
[array([3, 3, 6], dtype=int32), array([8, 7, 4], dtype=int32), array([6, 3, 2], dtype=int32)]

[array([3, 3, 6], dtype=int32), array([8, 7, 4], dtype=int32), array([6, 3, 2], dtype=int32)]



#                                          **11.3 ndarray Arithmetic Operators and Mathematical function**

In [6]:
import numpy as np

x1 = np.array([ 10, 20, 30, 100])
y1 = np.array ([2, 3, 4, 5])

add = x1+y1
print(add)

sub = x1-y1
print(sub)

div = x1/y1
print(div)

remainder = x1 % y1
print(remainder)

[12 23 34 45]
[ 8 17 26 35]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [15]:
sin_val = np.sin(x1)
print(sin_val)

cos_val = np.cos(x1)
print(cos_val)
print()
base_10_log = np.log10(x1)
print(base_10_log)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]

[1.         1.30103    1.47712125 1.60205999]


In [17]:
ase_10_log = np.log2(x1)
print(base_10_log)

[1.         1.30103    1.47712125 1.60205999]


In [19]:
sqr = np.sqrt(x1)
print(sqr)

[3.16227766 4.47213595 5.47722558 6.32455532]


In [20]:
s = np.sum(x1)
print(s)
cumul =np.cumulative_sum(x1)
print(cumul)

100
[ 10  30  60 100]



#            **11.4 Numpy Broadcasting**

In [26]:
x = np.array([10, 8 , 16 , 100])

result = x ** 2
#print(result)

mat = np.array([[10, 20, 30],
                [30, 40, 50]])

result = mat +2

vector = np.array([1, 2, 3])
result = mat +vector
print(result)

[[11 22 33]
 [31 42 53]]


# _**11.5 Numpy Logical Functions**_

In [27]:
x = np.array([10, 8 , 16 , 100])
y = np.array([2,3,4,5])

greater_than = x >y
print(greater_than)

equal = x==y
print(equal)

[ True  True  True  True]
[False False False False]


# **_11.6 ndarray Sorting_**

In [6]:
import numpy as np

x = np.array([10, 8 , 16 , 100])

z = x.copy()
print(z)

z.sort()
print(z)


[ 10   8  16 100]
[  8  10  16 100]


In [7]:
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [11]:
mat = np.array([[10, 3, 5],[8, 4, 9]])

horz_sort = np.sort(mat)
print(horz_sort)

vert_sort = np.sort(mat, axis=0)
print(vert_sort)


[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]
