In [2]:
from math import remainder
from signal import pthread_sigmask

import numpy as np

from extra_class import matrix
from numpy.ma.core import max_val

arr = np.random.randint(1, 100, size=(10, 5))
arr.shape

(10, 5)

In [5]:
b = arr.reshape(5,10)
b.shape
b.ndim
b

array([[62, 45, 35, 38, 38, 76, 91, 99, 11,  9],
       [56, 68, 72, 58, 67,  2,  7, 79, 68, 69],
       [56, 46, 81, 95, 50, 41, 95, 37, 75, 85],
       [87,  7, 12, 93, 69, 26, 56,  8, 85, 91],
       [19, 60, 81, 53, 60,  1, 13, 83, 39, 18]], dtype=int32)

In [7]:
flatten = b.flatten()

print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b, order='F')
print(column_wise_flattening)

1
[62 56 56 87 19 45 68 46  7 60 35 72 81 12 81 38 58 95 93 53 38 67 50 69
 60 76  2 41 26  1 91  7 95 56 13 99 79 37  8 83 11 68 75 85 39  9 69 85
 91 18]


In [9]:
a = np.random.randint(1, 10, size =(2,3))
b = np.random.randint(20, 30, size =(2,3))



In [11]:
con = np.concatenate((a, b), axis=0)
print(con)

[[ 1  5  4]
 [ 4  4  6]
 [26 26 20]
 [29 23 21]]


In [12]:
con_row = np.concatenate((a, b), axis=0)
print(con_row)
print()
con_col = np.concatenate((a, b), axis=1)
print(con_col)

[[ 1  5  4]
 [ 4  4  6]
 [26 26 20]
 [29 23 21]]

[[ 1  5  4 26 26 20]
 [ 4  4  6 29 23 21]]


In [14]:
x = np.random.randint(1, 10, size=(2,3))
y = np.random.randint(1, 10, size=(2,3))

r = np.concatenate((x, y), axis=0)
print(r)
print()
#print(x)
#print(y)

[[2 8 4]
 [8 2 7]
 [5 5 7]
 [9 4 9]]




#                            **11.2 ndarray Manipulation - 2**

In [4]:
import numpy as np

mat = np.array([[10, 20, 30],
                [30, 40, 50]])

transpose = mat.T
print(transpose)
print()
print(mat.shape)     # (2, 3)
print(transpose.shape)  # (3, 2)  ← উল্টে গেছে!

[[10 30]
 [20 40]
 [30 50]]

(2, 3)
(3, 2)


In [11]:
a = np.random.randint(1 ,10 , size =(9,))
print(a)
splitted_array = np.split(a,3)
print(splitted_array)
print()
splitted_array = np.split(a,3)
print(splitted_array)

[3 3 6 8 7 4 6 3 2]
[array([3, 3, 6], dtype=int32), array([8, 7, 4], dtype=int32), array([6, 3, 2], dtype=int32)]

[array([3, 3, 6], dtype=int32), array([8, 7, 4], dtype=int32), array([6, 3, 2], dtype=int32)]



#                                          **11.3 ndarray Arithmetic Operators and Mathematical function**

In [6]:
import numpy as np

x1 = np.array([ 10, 20, 30, 100])
y1 = np.array ([2, 3, 4, 5])

add = x1+y1
print(add)

sub = x1-y1
print(sub)

div = x1/y1
print(div)

remainder = x1 % y1
print(remainder)

[12 23 34 45]
[ 8 17 26 35]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [15]:
sin_val = np.sin(x1)
print(sin_val)

cos_val = np.cos(x1)
print(cos_val)
print()
base_10_log = np.log10(x1)
print(base_10_log)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]

[1.         1.30103    1.47712125 1.60205999]


In [17]:
ase_10_log = np.log2(x1)
print(base_10_log)

[1.         1.30103    1.47712125 1.60205999]


In [19]:
sqr = np.sqrt(x1)
print(sqr)

[3.16227766 4.47213595 5.47722558 6.32455532]


In [20]:
s = np.sum(x1)
print(s)
cumul =np.cumulative_sum(x1)
print(cumul)

100
[ 10  30  60 100]



#            **11.4 Numpy Broadcasting**

In [26]:
x = np.array([10, 8 , 16 , 100])

result = x ** 2
#print(result)

mat = np.array([[10, 20, 30],
                [30, 40, 50]])

result = mat +2

vector = np.array([1, 2, 3])
result = mat +vector
print(result)

[[11 22 33]
 [31 42 53]]


# _**11.5 Numpy Logical Functions**_

In [27]:
x = np.array([10, 8 , 16 , 100])
y = np.array([2,3,4,5])

greater_than = x >y
print(greater_than)

equal = x==y
print(equal)

[ True  True  True  True]
[False False False False]


# **_11.6 ndarray Sorting_**

In [6]:
import numpy as np

x = np.array([10, 8 , 16 , 100])

z = x.copy()
print(z)

z.sort()
print(z)


[ 10   8  16 100]
[  8  10  16 100]


In [7]:
print(x)
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [11]:
mat = np.array([[10, 3, 5],[8, 4, 9]])

horz_sort = np.sort(mat)
print(horz_sort)

vert_sort = np.sort(mat, axis=0)
print(vert_sort)


[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


# **_11.7 ndarray Searching_**

In [12]:
print(x)

[ 10   8  16 100]


In [16]:
index = np.where(x==8)
print(index)
index = np.where(x>8)
print(index)
index = np.where(x>8,x,0)
print(index)


(array([1]),)
(array([0, 2, 3]),)
[ 10   0  16 100]


In [18]:
index= np.where(mat>8)
print(index)
arr = np.where(mat>8,mat,0)
print(arr)


(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [20]:
x = np.array([10,100, 8 , 16 , 100])
max_val = np.argmax(x)
min_value = np.argmin(x)
print(min_value)
print(max_val)


2
1


# **_11.8 ndarray Counting_**

In [21]:
a = np.random.randint(1,100, size=(100,))
print(a)

[73 77 80 31 39 51 86 79 79 50 14 37 47 72 85 34 94 85  3 35 92 57 46 58
 32  3 31 54 67 81 80 63 81 23 72 37 57 62 76 20 35 83 83 57  6 37 40 89
 62 24 96 87 24 27 24 73  6 95 49 55  2 50 65 81  4 47 63 79 90 69 80 15
 20 71 56 25 83 14 36 10 66 85 15  5 59  3 66 95 12 57 76 52 71 93  2 43
 10 27 56 66]


In [29]:
val_grt_thn_60 = np.count_nonzero(a>10)
print(val_grt_thn_60)

89


In [30]:
unique_val = np.unique((a))
print(unique_val)

[ 2  3  4  5  6 10 12 14 15 20 23 24 25 27 31 32 34 35 36 37 39 40 43 46
 47 49 50 51 52 54 55 56 57 58 59 62 63 65 66 67 69 71 72 73 76 77 79 80
 81 83 85 86 87 89 90 92 93 94 95 96]


In [33]:
unique_val = np.unique(a,return_counts=True)
print(unique_val)

(array([ 2,  3,  4,  5,  6, 10, 12, 14, 15, 20, 23, 24, 25, 27, 31, 32, 34,
       35, 36, 37, 39, 40, 43, 46, 47, 49, 50, 51, 52, 54, 55, 56, 57, 58,
       59, 62, 63, 65, 66, 67, 69, 71, 72, 73, 76, 77, 79, 80, 81, 83, 85,
       86, 87, 89, 90, 92, 93, 94, 95, 96], dtype=int32), array([2, 3, 1, 1, 2, 2, 1, 2, 2, 2, 1, 3, 1, 2, 2, 1, 1, 2, 1, 3, 1, 1,
       1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 4, 1, 1, 2, 2, 1, 3, 1, 1, 2, 2, 2,
       2, 1, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 2, 1]))


In [31]:
unique_val = np.count_nonzero((a==30))
print(unique_val)

0


# **_11.9 Statistical function_**

In [ ]:
data = np.genfromtxt('student_scores.csv', delimiter=',',skip_header=1)
print(data)

In [41]:

math_marks = data[::,:1]

print(math_marks.T)

max_math_Marks = np.max(math_marks)
print(max_math_Marks)

min_math_Marks = np.min(math_marks)
print(min_math_Marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5


# **_11.10 Linear Algebra with NumPy_**

In [43]:
study_hours = np.array([2,4,5,7,8])
exam_scores = np.array([65,75,78,88,93])

data = np.array([study_hours, exam_scores])
correlation = np.corrcoef(data)
print(correlation)

[[1.         0.99855739]
 [0.99855739 1.        ]]


In [44]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# a er column and b er row same length hote hobe
dot_product = np.dot(A,B)
print(dot_product)


# trace
print(np.trace(B))

[[ 58  64]
 [139 154]]
17


In [45]:
sq_mat = np.array([[1,2,3],
          [4,5,6],
          [7,8,9]
         ])

det_of_sq = np.linalg.det(sq_mat)

rank_sq = np.linalg.matrix_rank(sq_mat)

print(det_of_sq)

print(rank_sq)

0.0
2


In [46]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]


# **_11.11 Problem Solving -1_**