In [3]:
import numpy as np

a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
print(b.shape)


(2, 3)


In [4]:
va = np.sin(np.pi/2)
print(va)

1.0


In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [13]:
a = np.array([3,2,1])
print(np.sort(a))

[1 2 3]


In [14]:
import numpy as np

# Define the matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Perform matrix multiplication
result = np.dot(A, B)

# Print the result
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nResult of dot(A, B):")
print(result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Result of dot(A, B):
[[19 22]
 [43 50]]
